- name: Updating/initialization the 2fa server and client.
  hosts: webhost
  remote_user: root
  tasks:
    - name: Synchronization of the webhost files.
      ansible.posix.synchronize:
        src: .
        dest: /opt
        delete: true
        owner: false
        group: false
        recursive: true
    - name: Stopping the webhost service (docker-compose down).
      community.docker.docker_compose:
        project_src: /opt/twofactorauth
        state: absent
    - name: Create and start services
      community.docker.docker_compose:
        build: true
        project_src: /opt/twofactorauth
        state: present
      register: output
    - name: Get the output of staring the service
      ansible.builtin.debug:
        var: output
