version: "3"
services:
  twofactorauth-client:
    build:
      context: ./login/twofactorauth/client
    networks:
      - app-network
    # ports: # testing purposes
    #   - 80:8080
  twofactorauth-server:
    build:
      context: ./login/twofactorauth/server
    networks:
      - app-network
    # ports: # testing purposes
    #   - 8090:80
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_local/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - twofactorauth-server
      - twofactorauth-client

networks:
  app-network:
    driver: bridge
